### ISSUE TITLE
Put in but not Russian

### ISSUE THREAD

**Issue by hawkiteo** [DevScouter/devscouter-front#6]
![드래곤볼스카우터](https://github.com/DevScouter/devscouter-front/assets/133576325/b1c52065-97bd-4485-90bb-846ba2ea041b)

Put this image in front page.

**Comment by MontyCoder0701** [comment]
Are you crazy?

**Comment by MontyCoder0701** [comment]
시봉방년아

**Comment by BLYKIM** [comment]
화이팅!
